# Generated by Django 4.1 on 2023-05-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="user",
        ),
    ]
